services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3101:3101'
    environment:
      - PORT=3101
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src
